In [1]:
import numpy as np
import scipy.linalg
import strawberryfields as sf

In [7]:
# Raw data
r11 = np.random.normal(0, 1)
r12 = np.random.normal(0, 1)
r13 = np.random.normal(0, 1)
r14 = np.random.normal(0, 1)
r22 = np.random.normal(0, 1)
r23 = np.random.normal(0, 1)
r24 = np.random.normal(0, 1)
r33 = np.random.normal(0, 1)
r34 = np.random.normal(0, 1)
r44 = np.random.normal(0, 1)
r = np.array([[r11, r12, r13, r14],
              [r12, r22, r23, r24],
              [r13, r23, r33, r34],
              [r14, r24, r34, r44]])
print("Raw data:")
print(r)
v11, v22, v33, v44 = r11, r22, r33, r44
v12 = (r12 - r11 - r22)/2
v14 = (r14 - r11 - r44)/2
v23 = (r23 - r22 - r33)/2
v34 = (r34 - r33 - r44)/2
v13 = 2 * r13 - r11 - r33
v24 = 2 * r24 - r22 - r44
v = np.array([[v11, v12, v13, v14],
              [v12, v22, v23, v24],
              [v13, v23, v33, v34],
              [v14, v24, v34, v44]])
print("Covariance matrix (xxpp):")
print(v)

Raw data:
[[ 0.21502155  0.29419381  0.88441646 -0.05532793]
 [ 0.29419381 -0.82527172  0.48230041  0.06544884]
 [ 0.88441646  0.48230041  1.71739653 -0.6205575 ]
 [-0.05532793  0.06544884 -0.6205575  -1.3754383 ]]
Covariance matrix (xxpp):
[[ 0.21502155  0.45222199 -0.16358517  0.55254441]
 [ 0.45222199 -0.82527172 -0.2049122   2.3316077 ]
 [-0.16358517 -0.2049122   1.71739653 -0.48125787]
 [ 0.55254441  2.3316077  -0.48125787 -1.3754383 ]]
