In [1]:
import numpy as np

In [2]:
def permutation_matrix(N):
    """
    生成 2N x 2N 的置换矩阵 P，
    用于将变量排序从 (xpxp) 变换为 (xxpp)。
    
    参数:
    N -- 量子模式的数量 (系统的维度)
    
    返回:
    P -- 置换矩阵 (2N x 2N)
    """
    P = np.zeros((2*N, 2*N))  # 创建 2N x 2N 的零矩阵

    for i in range(N):
        P[i, 2*i] = 1       # x_i 位置: 第 i 行从 2i 取值
        P[N + i, 2*i + 1] = 1  # p_i 位置: 第 (N+i) 行从 (2i+1) 取值

    return P

# 测试
N = 4  # 例如 3 维系统
P = permutation_matrix(N)
print(P)


[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [2]:
def symplectic_eigenvalues(M):
    n = M.shape[0] // 2
    J = np.block([[np.zeros((n, n)), np.eye(n)], [-np.eye(n), np.zeros((n, n))]])
    JM = J @ M
    eigenvalues = np.linalg.eigvals(JM)
    return np.sort(np.abs(eigenvalues))[:n]  # 取前 n 个非负辛特征值

# 示例矩阵（对称矩阵）
M = np.array([[2, 1, 0, 0],
              [1, 2, 0, 0],
              [0, 0, 3, 1],
              [0, 0, 1, 3]])

symplectic_eigs = symplectic_eigenvalues(M)
print("辛特征值:", symplectic_eigs)


辛特征值: [1.41421356 1.41421356]
