In [1]:
import numpy as np
from scipy.linalg import sqrtm
import scipy as sc
import matplotlib.pyplot as plt
import scipy
import random
import numba as numba
from numpy import complex128
from math import comb
from numba.typed import Dict
from numba import types
from scipy.optimize import curve_fit
from torch.optim import lr_scheduler
import torch
from tqdm import tqdm
import time
import csv
qumodes_number=100

In [8]:
import numpy as np

# 原始数据
data = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

# 要插入的一列数据
new_column = np.array([10, 11, 12])

# 在最前面插入一列数据
data_with_new_column = np.insert(data, 0, new_column, axis=1)

print("原始数据：")
print(data)
print("\n插入一列数据后的数据：")
print(data_with_new_column)


原始数据：
[[1 2 3]
 [4 5 6]
 [7 8 9]]

插入一列数据后的数据：
[[10  1  2  3]
 [11  4  5  6]
 [12  7  8  9]]


In [7]:
a1 * b1

array([[ 1,  4,  9],
       [ 4, 10, 18]])